'use strict';
const obsBranches=[
 ['Core system','core',['n0_2','n0_1','n0_0'],'The implemented computational engine, its framework, and authored formulation.','Organizes core methods'],
 ['Mathematics','math',['n0_0','n0_3','n0_4','n0_5','n7_0','n7_1','n7_2','n7_3','n7_5'],'Explore the geometry, operators, and mathematical manuscripts behind the framework.','Defines mathematical structures'],
 ['Training-free AI','signal',['n0_6','n1_2'],'Detection and runtime governance, evaluated under specific protocols.','Applies computational methods'],
 ['Control & energy','signal',['n0_7','n0_8','n7_4'],'Control research and resource-use evaluations, with simulations and physical measurements kept distinct.','Evaluates control applications'],
 ['Identity & learning','core',['n1_0','n1_1','n1_3'],'Dynamic identity architectures and measurable learning progression.','Proposes identity and learning applications'],
 ['Human signals','signal',['n2_0','n2_7','n2_8'],'Physiological signal research, measurement concepts, and public-health intelligence.','Studies biological applications'],
 ['Food systems','bio',['n2_1','n2_2','n2_3','n2_4','n2_5','n2_6'],'Food Coherence System, measurement devices, and the proposed food-to-body learning loop.','Develops food-system applications'],
 ['Bio-infrastructure','bio',['n3_0','n3_1','n3_2','n3_3','n3_4','n3_5','n3_6','n9_0','n9_1'],'Mycelium networks, regenerative construction, biohybrid sensing, and materials R&D.','Proposes regenerative infrastructure'],
 ['Space habitats','space',['n4_0','n4_1','n4_2'],'Bio-integrated transit habitats and closed-loop living systems for long-duration space.','Extends habitat design concepts'],
 ['Physical research','math',['n3_7','n8_0','n8_1','n8_2','n8_3','n8_4','n8_5','n8_6','n9_2','n9_3'],'Physical-engine hypotheses, optical concepts, quantum research, and holographic interfaces.','Explores physical extensions'],
 ['Research assets','signal',['n5_0','n5_1','n5_2','n5_3','n5_4','n5_5','n5_6'],'Benchmark assets, preserved failures, research communication, and reproducibility.','Documents evaluations and development'],
 ['Symbolic inquiry','symbolic',['n5_7','n6_0','n6_1','n6_2','n7_6','n9_4','n9_5'],'The Field Node Algorithm, birthday mathematics, Solexia, and symbolic or metaphysical inquiry.','Connects symbolic interpretations']
];
const obsCanvas=document.getElementById('observatory-canvas'),obsCtx=obsCanvas.getContext('2d'),obsScene=document.getElementById('scene');
const obsReduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
let obsW=1,obsH=1,obsYaw=.25,obsPitch=.12,obsActive=-1,obsRunning=false,obsFrame=0,obsLast=0,obsDrag=null,obsReveal=false,obsTick=0;
const obsPalette={core:'#96eddd',math:'#a9b8ff',signal:'#86c9f5',bio:'#b2df82',space:'#dfc29a',symbolic:'#d6acff'};
const obsNodes=[];
obsBranches.forEach((b,i)=>{for(const hostId of ['orbit-nodes','obs-lenses']){const btn=document.createElement('button');btn.className=hostId==='orbit-nodes'?'orbit-node':'obs-lens';btn.setAttribute('aria-pressed','false');const num=document.createElement('small');num.textContent=String(i+1).padStart(2,'0');const label=document.createElement('span');label.textContent=b[0];btn.append(num,label);btn.onclick=()=>obsSelect(i);document.getElementById(hostId).appendChild(btn);if(hostId==='orbit-nodes')obsNodes.push(btn)}});
function obsSelect(i){document.getElementById('inspect-core').textContent='Read core project';obsFocused=null;obsActive=i;const b=i<0?null:obsBranches[i];document.querySelectorAll('.obs-lens').forEach((x,j)=>x.setAttribute('aria-pressed',String(i===j)));obsNodes.forEach((x,j)=>x.setAttribute('aria-pressed',String(i===j)));obsScene.dataset.mode=b?b[1]:'core';obsScene.classList.toggle('branch-selected',i>=0);document.getElementById('scene-title').textContent=b?String(i+1).padStart(2,'0')+' / '+b[0].toUpperCase():'01 / CONNECTED RESEARCH';document.getElementById('scene-type').textContent=b&&b[1]==='bio'?'BIO-INTEGRATED SYSTEMS':b&&b[1]==='space'?'CLOSED-LOOP HABITAT':b&&b[1]==='signal'?'RELATIONAL TRAJECTORIES':b&&b[1]==='symbolic'?'SYMBOLIC RESEARCH':b?'12D MATHEMATICAL PROJECTION':'SPATIAL RESEARCH NETWORK';document.getElementById('inspector-kicker').textContent=b?'SELECTED RESEARCH LENS':'AT THE CENTER';document.getElementById('inspector-title').textContent=b?b[0]:'The Coherence Engine™';document.getElementById('inspector-description').textContent=b?b[3]:'The computational core for examining coherence, drift, instability, recovery, and changing system relationships.';const badge=document.getElementById('inspector-status');badge.textContent=b?'Development status in each project':'Implemented / benchmark-tested';badge.className='badge '+(b?(b[1]==='symbolic'?'symbolic':'proposed'):'built');document.getElementById('obs-lens-label').textContent=b?b[0]+' / '+b[2].length+' entries':'Explore the whole system';document.getElementById('scene-caption').textContent=b&&b[1]==='bio'?'Conceptual network and material layers. This scene is a design illustration, not a measured biological network.':b&&b[1]==='space'?'Conceptual habitat cutaway. Connections show proposed system roles, not a flight-ready engineering design.':b&&b[1]==='signal'?'Illustrative trajectories, not benchmark measurements. Open the evidence viewer for reported evaluations.':b&&b[1]==='symbolic'?'Symbolic and creative visualization. These interpretations are distinct from empirical findings.':b?'A projection of 12D geometry. Portfolio connections describe research organization, not physical equivalence.':'Every dot is a named project. Select one to trace its connections. Twelve lenses organize the portfolio; spatial depth is a navigation aid.';obsProjects(b);obsRelationships();obsDraw();}
function obsProjects(b){const host=document.getElementById('scene-projects');host.replaceChildren();const ids=b?b[2]:['n0_2','n0_6','n3_0','n4_2'];ids.forEach(id=>{const n=portfolioData.find(x=>x.id===id);if(!n)return;const btn=document.createElement('button');btn.className='inspector-project';const title=document.createElement('span');title.textContent=n.name;const arrow=document.createElement('span');arrow.textContent='↗';btn.append(title,arrow);btn.onclick=()=>details(n);host.appendChild(btn)})}
function obsRelationships(){const host=document.getElementById('relationship-list');host.hidden=!obsReveal;host.replaceChildren();if(!obsReveal)return;const heading=document.createElement('h3');heading.textContent='Relationship to core';host.appendChild(heading);const b=obsActive>=0?obsBranches[obsActive]:null;const p=document.createElement('p');p.textContent=b?'The Coherence Engine™ → '+b[4]+' → '+b[0]: 'Engine → methods → evaluations → proposed applications';host.appendChild(p);const note=document.createElement('small');note.textContent='Curated portfolio relationships. Shared organization does not establish a common physical mechanism.';host.appendChild(note)}
document.getElementById('engine-node').onclick=()=>obsSelect(-1);document.getElementById('inspect-core').onclick=()=>details(portfolioData.find(n=>n.id===(obsFocused||'n0_2')));
document.getElementById('obs-relations').onclick=()=>{obsReveal=!obsReveal;document.getElementById('obs-relations').setAttribute('aria-pressed',String(obsReveal));obsRelationships();obsDraw()};
document.getElementById('obs-reset').onclick=()=>{obsYaw=.25;obsPitch=.12;obsSelect(-1)};
document.getElementById('index-view').onclick=()=>{expanded=true;window.portfolioLens=null;search.value='';branch.value='';render();document.getElementById('projects').scrollIntoView({behavior:obsReduce?'auto':'smooth'});document.getElementById('index-view').setAttribute('aria-pressed','true');document.getElementById('spatial-view').setAttribute('aria-pressed','false')};
document.getElementById('spatial-view').onclick=()=>{document.getElementById('home').scrollIntoView({behavior:obsReduce?'auto':'smooth'});document.getElementById('index-view').setAttribute('aria-pressed','false');document.getElementById('spatial-view').setAttribute('aria-pressed','true')};
function obsProject(x,y,z){const xx=x*Math.cos(obsYaw)+z*Math.sin(obsYaw),zz=-x*Math.sin(obsYaw)+z*Math.cos(obsYaw),yy=y*Math.cos(obsPitch)-zz*Math.sin(obsPitch),depth=y*Math.sin(obsPitch)+zz*Math.cos(obsPitch),scale=Math.min(obsW,obsH)*.075*9/(9+depth);return [obsW/2+xx*scale,obsH/2+yy*scale,depth]}
function obsLine(a,b,color,alpha=1,width=1){obsCtx.strokeStyle=color;obsCtx.globalAlpha=alpha;obsCtx.lineWidth=width;obsCtx.beginPath();obsCtx.moveTo(a[0],a[1]);obsCtx.lineTo(b[0],b[1]);obsCtx.stroke();obsCtx.globalAlpha=1}
const obsBasis=Array.from({length:12},(_,i)=>{let z=1-2*(i+.5)/12,a=i*Math.PI*(3-Math.sqrt(5)),r=Math.sqrt(1-z*z);return [r*Math.cos(a),r*Math.sin(a),z]});
let obsSeed=72;function obsRandom(){obsSeed=(obsSeed*1664525+1013904223)>>>0;return obsSeed/4294967296}
const obsVertices=new Set();for(let i=0;i<20;i++){let v=Math.floor(obsRandom()*4096);obsVertices.add(v);for(let d=0;d<12;d++)obsVertices.add(v^(1<<d))}const obsPoints=[...obsVertices],obsEdges=[];obsPoints.forEach(v=>{for(let d=0;d<12;d++){let q=v^(1<<d);if(q>v&&obsVertices.has(q))obsEdges.push([v,q,d])}});
function obsHyperPoint(v){const coords=Array.from({length:12},(_,d)=>(v>>d&1)?1:-1);for(let d=0;d<12;d+=2){const a=obsTick*.11*(d+1),x=coords[d],y=coords[d+1];coords[d]=x*Math.cos(a)-y*Math.sin(a);coords[d+1]=x*Math.sin(a)+y*Math.cos(a)}const p=[0,0,0];coords.forEach((x,d)=>obsBasis[d].forEach((t,k)=>p[k]+=x*t));return obsProject(...p)}
function obsGeometry(color){const map=new Map(obsPoints.map(v=>[v,obsHyperPoint(v)]));obsEdges.forEach(([v,q,d])=>obsLine(map.get(v),map.get(q),color,obsReveal?.5:.17,obsReveal?1.2:.7));for(const [v,p] of map){obsCtx.fillStyle=color;obsCtx.globalAlpha=.45;obsCtx.beginPath();obsCtx.arc(p[0],p[1],1.5,0,Math.PI*2);obsCtx.fill()}obsCtx.globalAlpha=1}
const obsBio=[];function obsBranch(x,y,z,angle,len,depth){if(depth===0)return;const nx=x+Math.cos(angle)*len,ny=y+Math.sin(angle)*len,nz=z+Math.sin(depth*2.1)*.25;obsBio.push([[x,y,z],[nx,ny,nz],depth]);obsBranch(nx,ny,nz,angle-.5,len*.72,depth-1);obsBranch(nx,ny,nz,angle+.55,len*.7,depth-1)}for(let i=0;i<7;i++)obsBranch(0,0,0,i*Math.PI*2/7,1.5,5);
function obsBioDraw(color){for(let j=0;j<3;j++){const y=(j-1)*.65;const corners=[[-4,y,-2],[4,y,-2],[4,y,2],[-4,y,2]].map(p=>obsProject(...p));obsCtx.fillStyle=color;obsCtx.globalAlpha=.035;obsCtx.beginPath();corners.forEach((p,i)=>i?obsCtx.lineTo(...p.slice(0,2)):obsCtx.moveTo(...p.slice(0,2)));obsCtx.closePath();obsCtx.fill();obsCtx.globalAlpha=1;corners.forEach((p,i)=>obsLine(p,corners[(i+1)%4],color,.18))}obsBio.forEach(([a,b,d])=>{obsLine(obsProject(...a),obsProject(...b),color,.3+d*.08,d*.45);const p=obsProject(...b);obsCtx.fillStyle=color;obsCtx.beginPath();obsCtx.arc(p[0],p[1],d===1?2:1,0,Math.PI*2);obsCtx.fill()})}
function obsSpace(color){const loops=[];for(let x=-3.5;x<=3.5;x+=1.4){const pts=[];for(let i=0;i<24;i++){const a=i*Math.PI*2/24;pts.push(obsProject(x,1.55*Math.cos(a),1.55*Math.sin(a)))}loops.push(pts);pts.forEach((p,i)=>obsLine(p,pts[(i+1)%24],color,.45))}for(let j=0;j<24;j+=3)for(let i=1;i<loops.length;i++)obsLine(loops[i-1][j],loops[i][j],color,.35);const boxes=[[-2,-.4,0],[0,-.4,0],[2,-.4,0]];boxes.forEach(([x,y,z])=>{const vs=Array.from({length:8},(_,i)=>obsProject(x+(i&1?.65:-.65),y+(i&2?.6:-.6),z+(i&4?.6:-.6)));for(let i=0;i<8;i++)for(let d=0;d<3;d++){const q=i^(1<<d);if(q>i)obsLine(vs[i],vs[q],color,.6)}});const labels=[['LIVING SYSTEMS',-2],['HABITAT',0],['RESOURCE LOOP',2]];obsCtx.font='10px ui-monospace, monospace';obsCtx.fillStyle=color;labels.forEach(([t,x])=>{const p=obsProject(x,2.2,0);obsCtx.fillText(t,p[0]-35,p[1])})}
function obsSignals(color){for(let row=0;row<5;row++){let prev=null;for(let i=0;i<130;i++){const t=i/129,x=(t-.5)*9,y=(row-2)*.6+Math.sin(t*15+row*.35+obsTick*.2)*.25+Math.sin(t*40+row)*.06,z=Math.sin(t*6+row)*.55;const p=obsProject(x,y,z);if(prev)obsLine(prev,p,color,.3+row*.1,1.3);prev=p}}const a=obsProject(-3,2,0),b=obsProject(3,2,0);obsLine(a,b,color,.4);obsCtx.font='10px ui-monospace, monospace';obsCtx.fillStyle=color;obsCtx.fillText('ILLUSTRATIVE RELATIONAL TRAJECTORIES',a[0],a[1]+20)}
function obsSymbolic(color){for(let r=1;r<=4;r++){let prev=null;for(let i=0;i<=160;i++){const a=i*Math.PI*2/160,x=Math.cos(a)*r,y=Math.sin(a)*r*.5,z=Math.sin(a*3+obsTick*.15)*.4;const p=obsProject(x,y,z);if(prev)obsLine(prev,p,color,.2+r*.08);prev=p}}}

// A spatial projection of named portfolio nodes, rather than anonymous decorative vertices.
const obsProjectNodes=[];const obsProjectButtons=[];const obsProjectLinks=[];let obsFocused=null;
const obsSeen=new Set();obsBranches.forEach((b,bi)=>b[2].forEach((id,j)=>{if(obsSeen.has(id))return;obsSeen.add(id);const a=bi*Math.PI*2/12-Math.PI/2,spread=(j%3-1)*.24,r=2.3+(Math.floor(j/3)%3)*.45;obsProjectNodes.push({id,branch:bi,p:[Math.cos(a+spread)*r,Math.sin(a+spread)*r,Math.sin(j*2.3+bi)*1.6]});const btn=document.createElement('button');btn.className='spatial-project-dot';btn.setAttribute('aria-label',portfolioData.find(n=>n.id===id).name);btn.title=portfolioData.find(n=>n.id===id).name;btn.onclick=()=>obsFocusProject(id);document.getElementById('orbit-nodes').appendChild(btn);obsProjectButtons.push(btn);obsProjectLinks.push({a:'branch:'+bi,b:id,label:'Portfolio branch membership',kind:'organization'});}));
const obsCrossLinks=[
 ['n0_6','n5_0','Detection implementation → benchmark assets','documented'],
 ['n0_7','n0_8','Resource gating → control and energy research','research'],
 ['n2_1','n2_6','Food Coherence System → food-to-body learning loop','proposed'],
 ['n2_6','n1_3','Learning loop → measurable learning progression','proposed'],
 ['n3_0','n4_2','Bio-integrated infrastructure → proposed transit habitat','proposed'],
 ['n3_6','n2_0','Biohybrid sensing ↔ human-signal research','research'],
 ['n7_0','n0_0','Unified mathematical framework → authored field formulation','documented'],
 ['n7_4','n0_8','Arbitration control law → control research','research'],
 ['n9_0','n3_5','Myco-algae concrete → regenerative building research','research'],
 ['n9_1','n3_0','Mycelium plastic → bio-integrated materials research','research'],
 ['n9_2','n8_0','Quantum and physical-engine research branches','research'],
 ['n6_1','n9_5','Birth signature ↔ symbolic identity inquiry','symbolic']
];obsCrossLinks.forEach(([a,b,label,kind])=>obsProjectLinks.push({a,b,label,kind}));
function obsFocusProject(id){if(obsActive>=0)obsSelect(-1);obsFocused=id;document.getElementById('inspect-core').textContent='Read selected project';const n=portfolioData.find(x=>x.id===id);document.getElementById('inspector-kicker').textContent='NAMED PROJECT DOT';document.getElementById('inspector-title').textContent=n.name;document.getElementById('inspector-description').textContent=n.description;const badge=document.getElementById('inspector-status');badge.textContent='Evidence & status in project details';badge.className='badge';const host=document.getElementById('scene-projects');host.replaceChildren();const button=document.createElement('button');button.className='inspector-project';button.textContent='Read project and development status ↗';button.onclick=()=>details(n);host.appendChild(button);const related=obsProjectLinks.filter(e=>e.a===id||e.b===id);related.forEach(e=>{const other=e.a===id?e.b:e.a;const button=document.createElement('button');button.className='inspector-project';if(other.startsWith('branch:')){const bi=Number(other.split(':')[1]);button.textContent=obsBranches[bi][0]+' · '+e.label;button.onclick=()=>obsSelect(bi)}else{button.textContent=portfolioData.find(n=>n.id===other).name+' · '+e.label+' · '+e.kind;button.onclick=()=>obsFocusProject(other)}host.appendChild(button)});obsDraw()}
function obsSpatialNetwork(labelPositions){const points=new Map();labelPositions.forEach(([x,y,hw,hh],i)=>{const a=i*Math.PI*2/12-Math.PI/2,hub=[obsW/2+Math.cos(a)*obsW*.26,obsH/2+Math.sin(a)*obsH*.25];points.set('branch:'+i,hub);const dx=x-hub[0],dy=y-hub[1],trim=Math.min(Math.abs(dx)>0?hw/Math.abs(dx):Infinity,Math.abs(dy)>0?hh/Math.abs(dy):Infinity);if(obsW>540)obsLine(hub,[x-dx*trim,y-dy*trim],obsPalette[obsBranches[i][1]],.8,1.3);obsCtx.fillStyle=obsPalette[obsBranches[i][1]];obsCtx.beginPath();obsCtx.arc(hub[0],hub[1],5,0,Math.PI*2);obsCtx.fill();const dx0=hub[0]-obsW/2,dy0=hub[1]-obsH/2,l=Math.hypot(dx0,dy0),r=(document.getElementById('engine-node').offsetWidth||155)/2;obsLine([obsW/2+dx0/l*r,obsH/2+dy0/l*r],hub,obsPalette[obsBranches[i][1]],.2)});
 obsProjectNodes.forEach((n,i)=>{const p=obsProject(...n.p);points.set(n.id,p);obsProjectButtons[i].style.left=p[0]+'px';obsProjectButtons[i].style.top=p[1]+'px';obsProjectButtons[i].style.setProperty?.('--dot-color',obsPalette[obsBranches[n.branch][1]]);obsProjectButtons[i].setAttribute('aria-pressed',String(n.id===obsFocused));});
 obsProjectLinks.forEach(e=>{const a=points.get(e.a),b=points.get(e.b);if(!a||!b)return;const selected=e.a===obsFocused||e.b===obsFocused,shared=!e.a.startsWith('branch:'),color=e.kind==='symbolic'?'#d6acff':shared?'#a8e5de':obsPalette[obsBranches[Number(e.a.split(':')[1])][1]];obsLine(a,b,color,obsFocused?(selected?.95:.07):shared?(obsReveal?.8:.4):.35,selected?2:shared?1.2:.8)});
 obsProjectNodes.forEach(n=>{const p=points.get(n.id),selected=n.id===obsFocused;obsCtx.fillStyle=obsPalette[obsBranches[n.branch][1]];obsCtx.globalAlpha=obsFocused?(selected?1:.45):.9;obsCtx.beginPath();obsCtx.arc(p[0],p[1],selected?5:2.4,0,Math.PI*2);obsCtx.fill();});obsCtx.globalAlpha=1;
}
function obsDraw(){if(!obsCtx)return;obsCtx.clearRect(0,0,obsW,obsH);const mode=obsActive>=0?obsBranches[obsActive][1]:'core',color=obsPalette[mode];const g=obsCtx.createRadialGradient(obsW*.5,obsH*.5,10,obsW*.5,obsH*.5,obsW*.7);g.addColorStop(0,color+'18');g.addColorStop(1,'#080d1600');obsCtx.fillStyle=g;obsCtx.fillRect(0,0,obsW,obsH);obsCtx.fillStyle='#92a6bb';for(let i=0;i<70;i++){const x=((i*137.507)%100)/100*obsW,y=((i*53.113)%100)/100*obsH;obsCtx.globalAlpha=.15+(i%3)*.1;obsCtx.fillRect(x,y,1,1)}obsCtx.globalAlpha=1;if(mode==='bio')obsBioDraw(color);else if(mode==='space')obsSpace(color);else if(mode==='signal')obsSignals(color);else if(mode==='symbolic')obsSymbolic(color);else if(obsActive>=0)obsGeometry(color);
 const labels=[];
 obsNodes.forEach((node,i)=>{const a=i*Math.PI*2/12-Math.PI/2,rx=obsW*.37,ry=obsH*.35,hw=(node.offsetWidth||obsBranches[i][0].length*6+38)/2,hh=(node.offsetHeight||34)/2,x=Math.max(hw+14,Math.min(obsW-hw-14,obsW*.5+Math.cos(a)*rx)),y=obsH*.5+Math.sin(a)*ry;node.style.left=x+'px';node.style.top=y+'px';labels.push([x,y,hw,hh]);});
 obsProjectButtons.forEach(btn=>btn.hidden=obsActive>=0);if(obsActive<0)obsSpatialNetwork(labels);

}
function obsResize(){const r=obsCanvas.getBoundingClientRect();obsW=r.width;obsH=r.height;const dpr=Math.min(devicePixelRatio||1,2);obsCanvas.width=obsW*dpr;obsCanvas.height=obsH*dpr;obsCtx.setTransform(dpr,0,0,dpr,0,0);obsDraw()}new ResizeObserver(obsResize).observe(obsCanvas);
obsCanvas.addEventListener('pointerdown',e=>{obsDrag=[e.clientX,e.clientY];obsCanvas.setPointerCapture(e.pointerId)});obsCanvas.addEventListener('pointermove',e=>{if(!obsDrag)return;obsYaw+=(e.clientX-obsDrag[0])*.005;obsPitch=Math.max(-1,Math.min(1,obsPitch+(e.clientY-obsDrag[1])*.005));obsDrag=[e.clientX,e.clientY];obsDraw()});for(const event of ['pointerup','pointercancel'])obsCanvas.addEventListener(event,()=>obsDrag=null);obsCanvas.addEventListener('keydown',e=>{const d={ArrowLeft:[-.1,0],ArrowRight:[.1,0],ArrowUp:[0,-.1],ArrowDown:[0,.1]}[e.key];if(d){e.preventDefault();obsYaw+=d[0];obsPitch+=d[1];obsDraw()}});
function obsAnimate(t){if(!obsRunning)return;const dt=Math.min((t-obsLast)/1000,.05);obsLast=t;if(!obsDrag){obsYaw+=dt*.05;obsTick+=dt}obsDraw();obsFrame=requestAnimationFrame(obsAnimate)}function obsSetMotion(value){obsRunning=value;const b=document.getElementById('obs-motion');b.textContent=value?'Pause motion':'Start motion';b.setAttribute('aria-pressed',String(value));cancelAnimationFrame(obsFrame);if(value){obsLast=performance.now();obsFrame=requestAnimationFrame(obsAnimate)}}document.getElementById('obs-motion').onclick=()=>obsSetMotion(!obsRunning);document.addEventListener('visibilitychange',()=>{if(document.hidden)obsSetMotion(false)});obsSelect(-1);obsResize();
